---
name: Python Tests

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install tox
      - name: Validate formatting
        run: tox -e format

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
      # - name: Prepare artifacts
      #   run: mkdir -p .coverage-data && mv .coverage.* .coverage-data/
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-data
      #     path: .coverage-data/
